workflows:
  android-test-workflow:
    name: Android Test Workflow
    max_build_duration: 120
    environment:
      groups:
        - keystore_credentials # <-- (Includes CM_KEYSTORE, CM_KEYSTORE_PASSWORD, CM_KEY_PASSWORD, CM_KEY_ALIAS)
        - other # firebase_token
      vars:
        CM_KEYSTORE_PATH: /tmp/keystore.keystore
        PACKAGE_NAME: "uz.avotech.app.test"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up key properties
        script: |
          echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
          cat >> "$CM_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=/tmp/keystore.keystore
          EOF
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Adding Flutter pub to PATH
        script: |
          export PATH="$PATH":"$FLUTTER_ROOT/bin"
      - name: Adding dart  to PATH
        script: |
          export PATH="$PATH":"$FLUTTER_ROOT/bin/dart"
      - name:   echo path
        script: |
          echo $PATH
      - name: setup melos 
        script: |
          flutter pub global activate melos
      - name: Get dependencies
        script: |
          cd . && flutter pub global run melos bootstrap
      - name: Build AAB with Flutter
        script: |
          cd . && flutter build appbundle --release -—flavor qa —dart-define=APP_ENV=qa --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - djuraevshakhzod@gmail.com
